Feature/migrate genesis data cli
pointnetwork/pointnetwork pull request #159
Opened 2022-01-27 01:51 UTC by AlexandreCarvalhoDeMelo

2022-01-28 14:40 UTC, tankakatan reviewed
Please resolved the below issue. Also we will improve this scripts later on.

2022-01-28 14:40 UTC, tankakatan commented on scripts/blockchain/migrate-alpha-data.js
> +init = () => {
Please don't declare variables in the global scope. Use `const` statements instead.

2022-02-02 21:14 UTC, tankakatan requested changes

2022-02-02 21:14 UTC, tankakatan commented on scripts/blockchain/migrate-alpha-data.js
> +init = () => {
I think I wasn't clear in my previous comment. You moved the `if` statement and some other code inside the `init` function, but that's now what I mean.

What I mean is that you declare the `init` and other functions in this file without `const` keyword, which adds these function to the app's global scope. This is an anti-pattern, and we should avoid it. Please add `const` keywords for each function declaration here.

2022-02-09 11:11 UTC, jensendarren approved these changes

2022-02-09 12:59 UTC, brianunlam commented
Hi team, now we are running an eslint check that blocks the merging if there are some errors. Locally run "npm run fix" and fix not auto-fixable errors manually and then update the pr until check passes. Also you can add eslint comments in order to avoid some particular errors. Any doubt don't hesitate to contact me.

2022-02-15 06:08 UTC, merged