Zapp versions
pointnetwork/pointnetwork pull request #241
Opened 2022-03-01 19:15 UTC by diogosmendonca

Enable to use semantic versioning for ZApps and to access specific versions using __point_version request parameter. Currently, only Twitter.z is ready to be accessed using __point_version. All change state interaction with smart contracts when using __point_version are blocked with a 403 response.

2022-03-03 07:00 UTC, jensendarren commented
@diogosmendonca - Since there are changes made to the `Identity` contract in this PR can you confirm that once we redeploy the Identity contract and migrate all the Identities and all the `ikv` lists that we **do not** need to redeploy all the Zapps? This should be possible to test using our `zappdev` environment as follows:

- Start up a clean `zappdev` instance
- Deploy twitter.z and blog.z
- Redeploy the Identity contract to a new address using `truffle console`
- Update the node so that it now references this new Identity contract instance
- Run the `identityImporter.js` Truffle script to migrate the `ikv` list from the previous Identity contract instance to the new instance
- Test the twitter.z and blog.z Zapps still work
- Test the Point Explorer still works and is picking up the correct `ikv` list and versions

2022-03-03 09:00 UTC, jensendarren requested changes

2022-03-03 15:39 UTC, diogosmendonca commented on src/network/web3bridge.js
> +            return maxObj.returnValues.version;
Ok, done.

2022-03-03 15:42 UTC, diogosmendonca commented on src/client/storage/index-arlocal.js
> +            // It works in twitter.z, but brokes in pointsocial.z, for example.
Yes, it was fixed in develop branch. However, after testing pointsocial.z seems that the error happens for large files where there are more than one chunk. The problem was solved partially only. After rollback to our workaround everything worked fine.

2022-03-08 13:33 UTC, jensendarren approved these changes

2022-03-08 13:47 UTC, merged