Validate chunks are uploaded to arweave
pointnetwork/pointnetwork pull request #328
Opened 2022-04-01 18:23 UTC by brianunlam

2022-04-01 20:48 UTC, Koochr requested changes

2022-04-01 20:48 UTC, Koochr commented on src/client/storage/uploader.ts
> +        } catch (error) {
Why are you setting it to failed after the first failed attempt? We should implement some timeout or limit, after which it should be treated as failed. And, I think, this limit should be the DB field, same as we have for upload loop

2022-04-01 20:48 UTC, Koochr commented on src/client/storage/uploader.ts
>          // TODO: check status from bundler
I think this TODO won't be actual after your fixes

2022-04-04 12:48 UTC, tankakatan reviewed
Thanks, please see the comments below.

2022-04-04 12:48 UTC, tankakatan commented on src/client/storage/uploader.ts
> +    allCompletedChunks.forEach(async (chunk) => {
I would propose to limit the array length here. If for some reason there is a hundred chunks to verify, we are going to request them all at the same time which may be not efficient.

2022-04-04 12:48 UTC, tankakatan commented on src/client/storage/uploader.ts
> +const arweave = Arweave.init({
We already have a set up arweave client in the `storage` module. Is it possible to reuse it by creating a sort of `getDataByTxId` in the `storage` and use it  within the `chunkValidatorLoop` instead?

2022-04-07 14:13 UTC, tankakatan commented on src/client/storage/uploader.ts
> +const MAX_VALIDATION_CONCURRENCY = 100;
This should not be hard-coded here. Please add to `config/default.yaml` and `config/custom_env_variables.yaml` instead. There is a property `storage.concurrent_upload_limit` already. I think the `CONCURRENT_UPLOAD_LIMIT` variable is also used for that.

2022-04-08 07:37 UTC, tankakatan approved these changes

2022-04-08 07:37 UTC, merged