PN-175 Support CORS in proxy server
pointnetwork/pointnetwork pull request #477
Opened 2022-06-21 18:23 UTC by germanviescas

Supporting CORS in proxy is needed to get assets from the `mirror`. Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-175) for further details.

![cors](https://user-images.githubusercontent.com/101118664/174870878-edb66ac0-839c-4b7f-8e0e-c9bc7c40809e.png)

CORS is only enabled for requests to mirror.point.

These changes only handle _simple_ requests. We may need to also support _preflight_ requests, but since I haven't came across them just yet, we could add support for them later on (however, if you want me to do it now, let me know).

2022-06-22 09:25 UTC, tankakatan requested changes
Cross origin requests should not be allowed by default

2022-06-22 14:17 UTC, germanviescas commented on src/client/proxy/middleware/cors.ts
> +        // Hence, we allow all origins (*) for `https://mirror.point`.
This is intentional behaviour:

> If a cross-origin resource redirects to another resource at a new origin, the browser will set the value of the Origin header to null after redirecting. This prevents additional confused deputy attacks [...]

If you don't want the wildcard, please let me know and I'll see what we can do about it. The only thing that comes to mind is not redirecting, but perhaps there are other solutions I'm not aware of.

2022-06-27 20:54 UTC, tankakatan submitted a review, later dismissed
Please update the PR

2022-06-28 12:06 UTC, germanviescas commented
Conflicts with `develop` solved.

2022-06-30 19:54 UTC, tankakatan approved these changes

2022-06-30 19:54 UTC, merged